spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.faust0z.BookLibraryAPI: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cache: TRACE